CREATE DATABASE TPIGrupo29;
GO
USE TPIGrupo29;
GO

CREATE TABLE Ventas (
	IDVenta INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Fecha DATETIME NOT NULL DEFAULT GETDATE(),
	TipoFactura CHAR DEFAULT 'B',
	ImporteTotal FLOAT NOT NULL,
)
GO

CREATE TABLE MARCAS (
	IDMarca INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	Nombre NVARCHAR(100) NOT NULL,
)
GO

CREATE TABLE Articulos (
	IDArticulo INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	IDMarca INT NOT NULL,
	Nombre NVARCHAR(100) NOT NULL,
	Precio FLOAT NOT NULL,
	Eliminado BIT NOT NULL DEFAULT 0,

	FOREIGN KEY (IDMarca) REFERENCES Marcas (IDMarca),
)
GO

CREATE TABLE ArticulosVenta (
	IDVenta INT NOT NULL,
	IDArticulo INT NOT NULL,
	Cantidad INT NOT NULL,
	PrecioUnitario FLOAT NOT NULL

	PRIMARY KEY (IDVenta, IDArticulo)
	FOREIGN KEY (IDVenta) REFERENCES Ventas (IDVenta),
	FOREIGN KEY (IDarticulo) REFERENCES Articulos (IDArticulo),
)
GO

CREATE TABLE Stock (
	IDArticulo INT UNIQUE NOT NULL,
	Cantidad INT NOT NULL DEFAULT 0,

	FOREIGN KEY (IDArticulo) REFERENCES Articulos (IDArticulo)
)
GO